# 移除pod repo remove master的的警告：
# [!] Your project does not explicitly specify the CocoaPods master specs repo.
# Since CDN is now used as the default, you may safely remove it from your repos directory via `pod repo remove master`.
# To suppress this warning please add `warn_for_unused_master_specs_repo => false` to your Podfile.
install! 'cocoapods', warn_for_unused_master_specs_repo: false

source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'CmdCode' do
  use_frameworks!
 
  pod 'SnapKit', '~> 5.6'
  pod 'Kingfisher', '~> 6.0'
end




post_install do |installer|
  installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
               end
          end
  end
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
      xcconfig_path = config.base_configuration_reference.real_path
      xcconfig = File.read(xcconfig_path)
      xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
      File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
      end
  end
    
    
end
